package org.group18.back.Dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.group18.back.Entity.CategoryShop;
import org.group18.back.Entity.CategoryShopExample;

public interface CategoryShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    long countByExample(CategoryShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int deleteByExample(CategoryShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int insert(CategoryShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int insertSelective(CategoryShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    List<CategoryShop> selectByExample(CategoryShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    CategoryShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") CategoryShop record, @Param("example") CategoryShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByExample(@Param("record") CategoryShop record, @Param("example") CategoryShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByPrimaryKeySelective(CategoryShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_category_shop
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByPrimaryKey(CategoryShop record);
}