package org.group18.back.Dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.group18.back.Entity.GoodsSpecification;
import org.group18.back.Entity.GoodsSpecificationExample;

public interface GoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    long countByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int deleteByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int insert(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int insertSelective(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    List<GoodsSpecification> selectByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    GoodsSpecification selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") GoodsSpecification record, @Param("example") GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByExample(@Param("record") GoodsSpecification record, @Param("example") GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specification
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    int updateByPrimaryKey(GoodsSpecification record);
}