package org.group18.back.Dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.group18.back.Entity.OrderGoodsSpecificationN;
import org.group18.back.Entity.OrderGoodsSpecificationNExample;

public interface OrderGoodsSpecificationNMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    long countByExample(OrderGoodsSpecificationNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    int deleteByExample(OrderGoodsSpecificationNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    int insert(OrderGoodsSpecificationN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    int insertSelective(OrderGoodsSpecificationN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    List<OrderGoodsSpecificationN> selectByExample(OrderGoodsSpecificationNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderGoodsSpecificationN record, @Param("example") OrderGoodsSpecificationNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    int updateByExample(@Param("record") OrderGoodsSpecificationN record, @Param("example") OrderGoodsSpecificationNExample example);
}