package org.group18.back.Dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.group18.back.Entity.OrderType;
import org.group18.back.Entity.OrderTypeExample;

public interface OrderTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    long countByExample(OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int deleteByExample(OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int insert(OrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int insertSelective(OrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    List<OrderType> selectByExample(OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    OrderType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderType record, @Param("example") OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int updateByExample(@Param("record") OrderType record, @Param("example") OrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int updateByPrimaryKeySelective(OrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    int updateByPrimaryKey(OrderType record);
}