package org.group18.back.Entity;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.description
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.date
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.uid
     *
     * @return the value of t_category.uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.uid
     *
     * @param uid the value for t_category.uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.description
     *
     * @return the value of t_category.description
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.description
     *
     * @param description the value for t_category.description
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.date
     *
     * @return the value of t_category.date
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.date
     *
     * @param date the value for t_category.date
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}