package org.group18.back.Entity;

import java.io.Serializable;

public class CategoryShop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_shop.id
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_shop.category_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer categoryUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category_shop.shop_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer shopUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_category_shop
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_shop.id
     *
     * @return the value of t_category_shop.id
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_shop.id
     *
     * @param id the value for t_category_shop.id
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_shop.category_uid
     *
     * @return the value of t_category_shop.category_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getCategoryUid() {
        return categoryUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_shop.category_uid
     *
     * @param categoryUid the value for t_category_shop.category_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setCategoryUid(Integer categoryUid) {
        this.categoryUid = categoryUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category_shop.shop_uid
     *
     * @return the value of t_category_shop.shop_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getShopUid() {
        return shopUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category_shop.shop_uid
     *
     * @param shopUid the value for t_category_shop.shop_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setShopUid(Integer shopUid) {
        this.shopUid = shopUid;
    }
}