package org.group18.back.Entity;

import java.io.Serializable;
import java.util.Date;

public class GoodsReview implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.id
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.goods_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Integer goodsUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.goods_specification_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Integer goodsSpecificationUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.review
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private String review;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.level
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.date
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_review.user_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private String userUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_review
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.id
     *
     * @return the value of t_goods_review.id
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.id
     *
     * @param id the value for t_goods_review.id
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.goods_uid
     *
     * @return the value of t_goods_review.goods_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Integer getGoodsUid() {
        return goodsUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.goods_uid
     *
     * @param goodsUid the value for t_goods_review.goods_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setGoodsUid(Integer goodsUid) {
        this.goodsUid = goodsUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.goods_specification_uid
     *
     * @return the value of t_goods_review.goods_specification_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Integer getGoodsSpecificationUid() {
        return goodsSpecificationUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.goods_specification_uid
     *
     * @param goodsSpecificationUid the value for t_goods_review.goods_specification_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setGoodsSpecificationUid(Integer goodsSpecificationUid) {
        this.goodsSpecificationUid = goodsSpecificationUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.review
     *
     * @return the value of t_goods_review.review
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public String getReview() {
        return review;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.review
     *
     * @param review the value for t_goods_review.review
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setReview(String review) {
        this.review = review == null ? null : review.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.level
     *
     * @return the value of t_goods_review.level
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.level
     *
     * @param level the value for t_goods_review.level
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.date
     *
     * @return the value of t_goods_review.date
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.date
     *
     * @param date the value for t_goods_review.date
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_review.user_uid
     *
     * @return the value of t_goods_review.user_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public String getUserUid() {
        return userUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_review.user_uid
     *
     * @param userUid the value for t_goods_review.user_uid
     *
     * @mbg.generated Sun Jun 23 09:14:42 CST 2019
     */
    public void setUserUid(String userUid) {
        this.userUid = userUid == null ? null : userUid.trim();
    }
}