package org.group18.back.Entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.uid
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.category_uid
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private Integer categoryUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.discount_price
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private BigDecimal discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.amount
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.sales_volume
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private Integer salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.description
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.uid
     *
     * @return the value of t_goods.uid
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.uid
     *
     * @param uid the value for t_goods.uid
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.category_uid
     *
     * @return the value of t_goods.category_uid
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public Integer getCategoryUid() {
        return categoryUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.category_uid
     *
     * @param categoryUid the value for t_goods.category_uid
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setCategoryUid(Integer categoryUid) {
        this.categoryUid = categoryUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.discount_price
     *
     * @return the value of t_goods.discount_price
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.discount_price
     *
     * @param discountPrice the value for t_goods.discount_price
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.amount
     *
     * @return the value of t_goods.amount
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.amount
     *
     * @param amount the value for t_goods.amount
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.sales_volume
     *
     * @return the value of t_goods.sales_volume
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.sales_volume
     *
     * @param salesVolume the value for t_goods.sales_volume
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.description
     *
     * @return the value of t_goods.description
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.description
     *
     * @param description the value for t_goods.description
     *
     * @mbg.generated Mon Jun 24 10:24:30 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}