package org.group18.back.Entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrderGoodsSpecificationN implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.id
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.order_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private Integer orderUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.goods_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private Integer goodsUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.specification_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private Integer specificationUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.amount
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.price
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_n.discount_price
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private BigDecimal discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods_specification_n
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.id
     *
     * @return the value of t_order_goods_specification_n.id
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.id
     *
     * @param id the value for t_order_goods_specification_n.id
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.order_uid
     *
     * @return the value of t_order_goods_specification_n.order_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public Integer getOrderUid() {
        return orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.order_uid
     *
     * @param orderUid the value for t_order_goods_specification_n.order_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setOrderUid(Integer orderUid) {
        this.orderUid = orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.goods_uid
     *
     * @return the value of t_order_goods_specification_n.goods_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public Integer getGoodsUid() {
        return goodsUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.goods_uid
     *
     * @param goodsUid the value for t_order_goods_specification_n.goods_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setGoodsUid(Integer goodsUid) {
        this.goodsUid = goodsUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.specification_uid
     *
     * @return the value of t_order_goods_specification_n.specification_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public Integer getSpecificationUid() {
        return specificationUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.specification_uid
     *
     * @param specificationUid the value for t_order_goods_specification_n.specification_uid
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setSpecificationUid(Integer specificationUid) {
        this.specificationUid = specificationUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.amount
     *
     * @return the value of t_order_goods_specification_n.amount
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.amount
     *
     * @param amount the value for t_order_goods_specification_n.amount
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.price
     *
     * @return the value of t_order_goods_specification_n.price
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.price
     *
     * @param price the value for t_order_goods_specification_n.price
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_n.discount_price
     *
     * @return the value of t_order_goods_specification_n.discount_price
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_n.discount_price
     *
     * @param discountPrice the value for t_order_goods_specification_n.discount_price
     *
     * @mbg.generated Mon Jun 24 16:43:39 CST 2019
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }
}