package org.group18.back.Entity;

import java.io.Serializable;

public class OrderGoodsSpecificationY implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_y.id
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_y.order_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer orderUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_y.goods_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer goodsUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_y.specification_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer specificationUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_y.amount
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods_specification_y.points
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods_specification_y
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_y.id
     *
     * @return the value of t_order_goods_specification_y.id
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_y.id
     *
     * @param id the value for t_order_goods_specification_y.id
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_y.order_uid
     *
     * @return the value of t_order_goods_specification_y.order_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getOrderUid() {
        return orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_y.order_uid
     *
     * @param orderUid the value for t_order_goods_specification_y.order_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setOrderUid(Integer orderUid) {
        this.orderUid = orderUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_y.goods_uid
     *
     * @return the value of t_order_goods_specification_y.goods_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getGoodsUid() {
        return goodsUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_y.goods_uid
     *
     * @param goodsUid the value for t_order_goods_specification_y.goods_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setGoodsUid(Integer goodsUid) {
        this.goodsUid = goodsUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_y.specification_uid
     *
     * @return the value of t_order_goods_specification_y.specification_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getSpecificationUid() {
        return specificationUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_y.specification_uid
     *
     * @param specificationUid the value for t_order_goods_specification_y.specification_uid
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setSpecificationUid(Integer specificationUid) {
        this.specificationUid = specificationUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_y.amount
     *
     * @return the value of t_order_goods_specification_y.amount
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_y.amount
     *
     * @param amount the value for t_order_goods_specification_y.amount
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods_specification_y.points
     *
     * @return the value of t_order_goods_specification_y.points
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods_specification_y.points
     *
     * @param points the value for t_order_goods_specification_y.points
     *
     * @mbg.generated Sat Jun 22 16:48:21 CST 2019
     */
    public void setPoints(Integer points) {
        this.points = points;
    }
}