package org.group18.back.Entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(String value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(String value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(String value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(String value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(String value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(String value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLike(String value) {
            addCriterion("sn like", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotLike(String value) {
            addCriterion("sn not like", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<String> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<String> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(String value1, String value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(String value1, String value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNull() {
            addCriterion("discount_price is null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNotNull() {
            addCriterion("discount_price is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceEqualTo(BigDecimal value) {
            addCriterion("discount_price =", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotEqualTo(BigDecimal value) {
            addCriterion("discount_price <>", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThan(BigDecimal value) {
            addCriterion("discount_price >", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price >=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThan(BigDecimal value) {
            addCriterion("discount_price <", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price <=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIn(List<BigDecimal> values) {
            addCriterion("discount_price in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotIn(List<BigDecimal> values) {
            addCriterion("discount_price not in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price not between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andStateUidIsNull() {
            addCriterion("state_uid is null");
            return (Criteria) this;
        }

        public Criteria andStateUidIsNotNull() {
            addCriterion("state_uid is not null");
            return (Criteria) this;
        }

        public Criteria andStateUidEqualTo(String value) {
            addCriterion("state_uid =", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidNotEqualTo(String value) {
            addCriterion("state_uid <>", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidGreaterThan(String value) {
            addCriterion("state_uid >", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidGreaterThanOrEqualTo(String value) {
            addCriterion("state_uid >=", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidLessThan(String value) {
            addCriterion("state_uid <", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidLessThanOrEqualTo(String value) {
            addCriterion("state_uid <=", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidLike(String value) {
            addCriterion("state_uid like", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidNotLike(String value) {
            addCriterion("state_uid not like", value, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidIn(List<String> values) {
            addCriterion("state_uid in", values, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidNotIn(List<String> values) {
            addCriterion("state_uid not in", values, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidBetween(String value1, String value2) {
            addCriterion("state_uid between", value1, value2, "stateUid");
            return (Criteria) this;
        }

        public Criteria andStateUidNotBetween(String value1, String value2) {
            addCriterion("state_uid not between", value1, value2, "stateUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidIsNull() {
            addCriterion("type_uid is null");
            return (Criteria) this;
        }

        public Criteria andTypeUidIsNotNull() {
            addCriterion("type_uid is not null");
            return (Criteria) this;
        }

        public Criteria andTypeUidEqualTo(String value) {
            addCriterion("type_uid =", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidNotEqualTo(String value) {
            addCriterion("type_uid <>", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidGreaterThan(String value) {
            addCriterion("type_uid >", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidGreaterThanOrEqualTo(String value) {
            addCriterion("type_uid >=", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidLessThan(String value) {
            addCriterion("type_uid <", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidLessThanOrEqualTo(String value) {
            addCriterion("type_uid <=", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidLike(String value) {
            addCriterion("type_uid like", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidNotLike(String value) {
            addCriterion("type_uid not like", value, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidIn(List<String> values) {
            addCriterion("type_uid in", values, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidNotIn(List<String> values) {
            addCriterion("type_uid not in", values, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidBetween(String value1, String value2) {
            addCriterion("type_uid between", value1, value2, "typeUid");
            return (Criteria) this;
        }

        public Criteria andTypeUidNotBetween(String value1, String value2) {
            addCriterion("type_uid not between", value1, value2, "typeUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNull() {
            addCriterion("user_uid is null");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNotNull() {
            addCriterion("user_uid is not null");
            return (Criteria) this;
        }

        public Criteria andUserUidEqualTo(String value) {
            addCriterion("user_uid =", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotEqualTo(String value) {
            addCriterion("user_uid <>", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThan(String value) {
            addCriterion("user_uid >", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThanOrEqualTo(String value) {
            addCriterion("user_uid >=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThan(String value) {
            addCriterion("user_uid <", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThanOrEqualTo(String value) {
            addCriterion("user_uid <=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLike(String value) {
            addCriterion("user_uid like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotLike(String value) {
            addCriterion("user_uid not like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIn(List<String> values) {
            addCriterion("user_uid in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotIn(List<String> values) {
            addCriterion("user_uid not in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidBetween(String value1, String value2) {
            addCriterion("user_uid between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotBetween(String value1, String value2) {
            addCriterion("user_uid not between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidIsNull() {
            addCriterion("seller_uid is null");
            return (Criteria) this;
        }

        public Criteria andSellerUidIsNotNull() {
            addCriterion("seller_uid is not null");
            return (Criteria) this;
        }

        public Criteria andSellerUidEqualTo(String value) {
            addCriterion("seller_uid =", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotEqualTo(String value) {
            addCriterion("seller_uid <>", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidGreaterThan(String value) {
            addCriterion("seller_uid >", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidGreaterThanOrEqualTo(String value) {
            addCriterion("seller_uid >=", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidLessThan(String value) {
            addCriterion("seller_uid <", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidLessThanOrEqualTo(String value) {
            addCriterion("seller_uid <=", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidLike(String value) {
            addCriterion("seller_uid like", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotLike(String value) {
            addCriterion("seller_uid not like", value, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidIn(List<String> values) {
            addCriterion("seller_uid in", values, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotIn(List<String> values) {
            addCriterion("seller_uid not in", values, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidBetween(String value1, String value2) {
            addCriterion("seller_uid between", value1, value2, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andSellerUidNotBetween(String value1, String value2) {
            addCriterion("seller_uid not between", value1, value2, "sellerUid");
            return (Criteria) this;
        }

        public Criteria andIsPaidIsNull() {
            addCriterion("is_paid is null");
            return (Criteria) this;
        }

        public Criteria andIsPaidIsNotNull() {
            addCriterion("is_paid is not null");
            return (Criteria) this;
        }

        public Criteria andIsPaidEqualTo(Boolean value) {
            addCriterion("is_paid =", value, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidNotEqualTo(Boolean value) {
            addCriterion("is_paid <>", value, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidGreaterThan(Boolean value) {
            addCriterion("is_paid >", value, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_paid >=", value, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidLessThan(Boolean value) {
            addCriterion("is_paid <", value, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidLessThanOrEqualTo(Boolean value) {
            addCriterion("is_paid <=", value, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidIn(List<Boolean> values) {
            addCriterion("is_paid in", values, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidNotIn(List<Boolean> values) {
            addCriterion("is_paid not in", values, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidBetween(Boolean value1, Boolean value2) {
            addCriterion("is_paid between", value1, value2, "isPaid");
            return (Criteria) this;
        }

        public Criteria andIsPaidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_paid not between", value1, value2, "isPaid");
            return (Criteria) this;
        }

        public Criteria andMethodUidIsNull() {
            addCriterion("method_uid is null");
            return (Criteria) this;
        }

        public Criteria andMethodUidIsNotNull() {
            addCriterion("method_uid is not null");
            return (Criteria) this;
        }

        public Criteria andMethodUidEqualTo(String value) {
            addCriterion("method_uid =", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidNotEqualTo(String value) {
            addCriterion("method_uid <>", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidGreaterThan(String value) {
            addCriterion("method_uid >", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidGreaterThanOrEqualTo(String value) {
            addCriterion("method_uid >=", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidLessThan(String value) {
            addCriterion("method_uid <", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidLessThanOrEqualTo(String value) {
            addCriterion("method_uid <=", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidLike(String value) {
            addCriterion("method_uid like", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidNotLike(String value) {
            addCriterion("method_uid not like", value, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidIn(List<String> values) {
            addCriterion("method_uid in", values, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidNotIn(List<String> values) {
            addCriterion("method_uid not in", values, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidBetween(String value1, String value2) {
            addCriterion("method_uid between", value1, value2, "methodUid");
            return (Criteria) this;
        }

        public Criteria andMethodUidNotBetween(String value1, String value2) {
            addCriterion("method_uid not between", value1, value2, "methodUid");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsIsNull() {
            addCriterion("paid_by_points is null");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsIsNotNull() {
            addCriterion("paid_by_points is not null");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsEqualTo(Boolean value) {
            addCriterion("paid_by_points =", value, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsNotEqualTo(Boolean value) {
            addCriterion("paid_by_points <>", value, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsGreaterThan(Boolean value) {
            addCriterion("paid_by_points >", value, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("paid_by_points >=", value, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsLessThan(Boolean value) {
            addCriterion("paid_by_points <", value, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsLessThanOrEqualTo(Boolean value) {
            addCriterion("paid_by_points <=", value, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsIn(List<Boolean> values) {
            addCriterion("paid_by_points in", values, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsNotIn(List<Boolean> values) {
            addCriterion("paid_by_points not in", values, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsBetween(Boolean value1, Boolean value2) {
            addCriterion("paid_by_points between", value1, value2, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByPointsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("paid_by_points not between", value1, value2, "paidByPoints");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyIsNull() {
            addCriterion("paid_by_money is null");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyIsNotNull() {
            addCriterion("paid_by_money is not null");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyEqualTo(Boolean value) {
            addCriterion("paid_by_money =", value, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyNotEqualTo(Boolean value) {
            addCriterion("paid_by_money <>", value, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyGreaterThan(Boolean value) {
            addCriterion("paid_by_money >", value, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("paid_by_money >=", value, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyLessThan(Boolean value) {
            addCriterion("paid_by_money <", value, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyLessThanOrEqualTo(Boolean value) {
            addCriterion("paid_by_money <=", value, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyIn(List<Boolean> values) {
            addCriterion("paid_by_money in", values, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyNotIn(List<Boolean> values) {
            addCriterion("paid_by_money not in", values, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyBetween(Boolean value1, Boolean value2) {
            addCriterion("paid_by_money between", value1, value2, "paidByMoney");
            return (Criteria) this;
        }

        public Criteria andPaidByMoneyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("paid_by_money not between", value1, value2, "paidByMoney");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 24 18:23:20 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}