package org.group18.back.Entity;

import java.io.Serializable;

public class Shop implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.uid
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.shop_name
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.img_url
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.describes
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private String describes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.address
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.seller_uid
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private String sellerUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shop
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.uid
     *
     * @return the value of t_shop.uid
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.uid
     *
     * @param uid the value for t_shop.uid
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.shop_name
     *
     * @return the value of t_shop.shop_name
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.shop_name
     *
     * @param shopName the value for t_shop.shop_name
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.img_url
     *
     * @return the value of t_shop.img_url
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.img_url
     *
     * @param imgUrl the value for t_shop.img_url
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.describes
     *
     * @return the value of t_shop.describes
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.describes
     *
     * @param describes the value for t_shop.describes
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.address
     *
     * @return the value of t_shop.address
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.address
     *
     * @param address the value for t_shop.address
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.seller_uid
     *
     * @return the value of t_shop.seller_uid
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public String getSellerUid() {
        return sellerUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.seller_uid
     *
     * @param sellerUid the value for t_shop.seller_uid
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setSellerUid(String sellerUid) {
        this.sellerUid = sellerUid == null ? null : sellerUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.type
     *
     * @return the value of t_shop.type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.type
     *
     * @param type the value for t_shop.type
     *
     * @mbg.generated Mon Jun 24 18:23:20 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}