package org.group18.back.Entity;

import java.io.Serializable;
import java.util.Date;

public class Ticket implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.id
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.user_email
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.expire_date
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.is_time_out
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    private Boolean isTimeOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ticket.ticket
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    private String ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_ticket
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.id
     *
     * @return the value of t_ticket.id
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.id
     *
     * @param id the value for t_ticket.id
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.user_email
     *
     * @return the value of t_ticket.user_email
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.user_email
     *
     * @param userEmail the value for t_ticket.user_email
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.expire_date
     *
     * @return the value of t_ticket.expire_date
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.expire_date
     *
     * @param expireDate the value for t_ticket.expire_date
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.is_time_out
     *
     * @return the value of t_ticket.is_time_out
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public Boolean getIsTimeOut() {
        return isTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.is_time_out
     *
     * @param isTimeOut the value for t_ticket.is_time_out
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public void setIsTimeOut(Boolean isTimeOut) {
        this.isTimeOut = isTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ticket.ticket
     *
     * @return the value of t_ticket.ticket
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ticket.ticket
     *
     * @param ticket the value for t_ticket.ticket
     *
     * @mbg.generated Mon Jun 24 17:11:39 CST 2019
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }
}